# Gradle properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod properties
mod_id=backrooms_terralith_compat
mod_name=Backrooms-Terralith Compatibility Fix
mod_version=1.0.0
mod_group_id=com.trioxide.backroomscompat
mod_authors=TrioxideMods

# Minecraft properties
minecraft_version=1.20.1
forge_version=47.2.0
terrablender_version=1.20.1-3.0.0.167
