modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="faithfulbackrooms"
version="0.2"
displayName="Faithful Backrooms"
displayURL="https://patreon.com/faithfulbackrooms"
logoFile="logo.png"
credits="WhyAntique (WAEdition), Forameus (Original Edition), llkiur (Retired Texture Artist)"
authors="whyantique"
description="faithful_backrooms::wa_edition"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.faithfulbackrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.faithfulbackrooms]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.faithfulbackrooms]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration