modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
mixins = []
issueTrackerURL = "https://github.com/Apollounknowndev/tectonic/issues"

[[dependencies.tectonic]]
modId = "forge"
type = "required"
mandatory = true
versionRange = "[47,)"

[[dependencies.tectonic]]
modId = "lithostitched"
mandatory = true
type = "required"
versionRange = "[1.4.11,)"

[[mods]]
modId = "tectonic"
version = "3.0.17"
displayName = "Tectonic"
description = "Terrain shaping brought to new heights, grander and more varied than ever before!"
logoFile = "pack.png"
displayURL = "https://modrinth.com/project/tectonic"
credits = "Contributors: HB Stratos, DawnKiro, Uni"
authors = "Apollo"
